### ISSUE TITLE
Memory leak on macOS Catalina

### ISSUE THREAD

**Issue by inejge** [sfackler/rust-native-tls#171]
The following program repeatedly opens and drops a connection to a TLS endpoint (could be HTTPS, LDAPS, or anything that unconditionally negotiates TLS) and prints the amount of memory used by the program, as reported by `getrusage()`. On macOS Catalina, memory usage steadily increases with each iteration. The only earlier macOS I could test was El Capitan (10.11.x), and there the usage stabilized and stayed approximately constant after a while. Likewise on Linux (Ubuntu 18.04 LTS).

```rust
// libc = "0.2.71"
// native-tls = "0.2.4"

use std::env;
use std::error::Error;
use std::mem::MaybeUninit;
use std::net::TcpStream;
use std::time::Duration;
use std::thread;

use native_tls::TlsConnector;

#[cfg(target_os = "macos")]
const RSS_DIV: libc::c_long = 1024;

#[cfg(not(target_os = "macos"))]
const RSS_DIV: libc::c_long = 1;

fn main() -> Result<(), Box<dyn Error>> {
    let host_port = env::var("CATALINA_TLS_TEST")?;
    let hostname = host_port.split(':').next().ok_or("no host/port")?;
    loop {
        let stream = TcpStream::connect(&host_port)?;
        let mut builder = TlsConnector::builder();
        let mut rusage = MaybeUninit::<libc::rusage>::uninit();
        let rc = unsafe { libc::getrusage(0, rusage.as_mut_ptr()) };
        if rc == 0 {
            let rusage = unsafe { rusage.assume_init() };
            println!("rss: {}", rusage.ru_maxrss / RSS_DIV);
        }
        builder.danger_accept_invalid_certs(true);
        let connector = builder.build().expect("connector");
        let _stream = connector.connect(hostname, stream)?;
        thread::sleep(Duration::from_millis(100));
    }
}
```

The program expects to find the `host:port` pair in the environment variable `CATALINA_TLS_TEST`.

**Comment by sfackler** [comment]
Running in Instruments with the allocation tracker, we can see where the leaked memory is coming from in the steady-state of a similar test program:

<img width="1396" alt="Screen Shot 2020-05-31 at 2 12 37 PM" src="https://user-images.githubusercontent.com/1455697/83359577-12b4cb80-a349-11ea-8fb7-31a3e9ccd2f7.png">

It appears to be two specific allocations inside of Security.framework's internals. There's a bunch of other allocations involved in the handshake process that are freed, so this sounds like a bug in Security.framework to me. If it is the fault of the Rust side, this issue should probably be filed on the security-framework crate, since that's the thing interfacing with Security.framework.

**Comment by inejge** [comment]
Right, it's macOS-specific, but I figured that most people would probably encounter the problem through `native-tls`, hence the report here. Anyway, I opened a parallel issue in the `rust-security-framework` repo.

**Comment by sfackler** [comment]
Cool - I will close this in favor of that then.
