### ISSUE TITLE
Certificate and hostname verification

### ISSUE THREAD

**Issue by drbo** [sfackler/rust-native-tls#2]
Certificate and hostname verification should be enabled by default.

**Comment by sfackler** [comment]
Certificate verification (should) be enabled right now. Hostname verification is enabled with SChannel and Secure Transport since they handle it automatically, but not with OpenSSL since it doesn't. I'm working on writing a manual implementation for OpenSSL right now, and am currently working through some features on the rust-openssl side to enable access to subject alt names.

**Comment by sfackler** [comment]
This is now implemented for OpenSSL: https://github.com/sfackler/rust-native-tls/commit/b04c843fce86711d1a1d4af2913e46b68e44f360

It's not well tested, but that'll have to wait until trusted CAs can be specified.
