### ISSUE TITLE
Allow trusted certificates to be registered

### ISSUE THREAD

**Issue by sfackler** [sfackler/rust-native-tls#3]
This is straighforward for OpenSSL and Secure Transport, but I'm not sure how to do it with SChannel. We'll need to support both the addition of certs to the existing set as well as replacing the trusted set entirely.

Getting the cert out of PEM into a `CERT_CONTEXT` looks to be doable via `CryptStringToBinary` and `CertCreateCertificateContext`, but I still need to figure it out from there.

cc @retep998 - do you know how SChannel would do this?

**Comment by steffengy** [comment]
@sfackler 
I think one would need to implement manual certificate verification to perform checks like these,
since currently verification is handled by the default windows trust provider.
(there's also a TODO for that in the code)

https://msdn.microsoft.com/en-us/library/windows/desktop/aa378740(v=vs.85).aspx

**Comment by sfackler** [comment]
Windows does things in a very different way - you create a Certificate Trust List which needs to be signed by something with a trusted root. Unless we can force people to install a custom root cert (not reasonable), we may have to manually handle this. The OSCrypto library manually checks the root certificate in the trust chain against its extra roots: https://github.com/wbond/oscrypto/blob/master/oscrypto/_win/tls.py#L591
